### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.

### ISSUE THREAD

**Issue by hongdd** [yaxingwang/Transferring-GANs#6]
HI! 
I got tow errors,and do not know to solve it.
my computer:
tf:1.13.1 python:3.7
GPU:1060TI 6G

2019-03-28 21:37:47.625690: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-03-28 21:37:47.709614: E **tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.**
2019-03-28 21:37:48.412559: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-03-28 21:37:48.446716: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:704] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-03-28 21:37:49.504099: E tensorflow/core/common_runtime/executor.cc:624] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropInputOp only supports NHWC.
     [[{{node gradients/Discriminator.Res4.Shortcut_2/Conv2D_grad/Conv2DBackpropInput}}]]
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
**tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.**
     [[{{node gradients/Discriminator.Res4.Shortcut_2/Conv2D_grad/Conv2DBackpropInput}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Transferring-GANs-master\Transferring-GANs-master\transfer_gan.py", line 353, in <module>
    feed_dict={all_real_data_conv: _images, all_real_labels: _labels})
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
### tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.

so,hoping your reply.

**Comment by yaxingwang** [comment]
Hi, thank you for your interesting. 
Is the order of the tensor in your tensorflow is the same as NHWC?
It seems the error is from the point.
